config/routes.rb
Rails.application.routes.draw do

root 'he#home'
  match '/home',    to: 'he#home',    via: 'get'
      match '/home',    to: 'he#home',    via: 'post'


  match '/coder',    to: 'he#coder',    via: 'get'
    match '/coder',    to: 'he#coder',    via: 'post'


  match '/about',    to: 'he#about',    via: 'get'
  
  match '/update',    to: 'he#update',    via: 'get'
  match '/update',    to: 'he#update',    via: 'post'
  
    match '/update',    to: 'he#update',    via: 'get'
    
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/he_controller.rb
class HeController < ApplicationController

 
$tek=["text" => 'gfvsera', 'key' => 7]
$enko=["text" => 'gfvsera', 'key' => 5]

  $encoder='tada'
  $decoder='data'
  
  def home
  end

  def coder
 
  end

  def about
  end
  


def decoder_params
      params.require(:decoder).permit('enk','key')
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/he_helper.rb
module HeHelper
end

app/views/he-small-keys/_decoder.html.erb
<%= form_for $decoder do |form| %>
<%= form.label $decoder %>
<%= form.hidden_field $enko=params[$decoder] || {"enk"=>"", "key"=>5} %>


<% 
puts 'enko here'
puts $enko['enk']
puts $enko['key']
puts $enko


enko=$enko['enk']
key=$enko['key'].to_i
key=5 if $enko['key'].size==0 
####Внимание!!!! Нужно как-то запретить ставить нолик. Либо вместо этого использовать что-то другое.

puts 
puts 
puts ''
puts key
puts key.class

signa=("f"*key).to_i(16).to_s(10).size




puts "Convert into DEC:"
enko=enko.to_i(16).to_s(10)
puts enko

puts "Adding zeroes for square table"
enko='0'*(-enko.size%signa)+enko
puts enko

puts "Splitting into signa-amount of charachters:"
enkoma =enko.scan(/.{#{signa}}/)
puts enkoma

puts "Now converting the array into hex:"
enkoma.map! do |c|
c=c.to_i(10).to_s(16).rjust(key,'0')
end
puts
puts enkoma

#puts "Now removing placeholder zeroes:"
#enkoma[0]=enkoma[0].to_i
#puts enkoma



puts "Now join it into one block:"
enko=enkoma.join
puts enko

puts
#qwant=-enko.length%key
#puts qwant

#enko=enko[qwant..-1]

puts "Removing leading zeroes"
enko

enko=enko.sub(/^[0]+/,'')

puts "Converting back to human language:"
deko= [enko].pack("H*")
puts enko


#$enko['text']=enko

%>


  <%= form.label 'decoded' %>
<%= form.text_area :enk, value: $enko['enk']  %><P>
<%= text_area_tag 'decoded', deko   %>


    <%= form.label 'key' %>
    <%= form.text_field :key, value: $enko['key'] %>
        <P>
  <%= 
  	if params['commit']!='Decode!' then 
  
form.submit "Decode!"  
else 

link_to "<button>New Decode!</button>".html_safe, coder_path, :method => :get
end


%>
<P>
<%# form.label :text, value: $enko  %>

<%# form.text_field [$decoder], value:'teet'%>

<%#
puts 'this is for debug'
puts params[$decoder]
puts 'reset'
params.delete(/\D/) if params[$decoder]
puts params[$decoder]

%>



<div class="field">

</div>
   
<% end  %>

app/views/he-small-keys/_encoder.html.erb
<%= form_for $encoder do |form| %>
<%= form.label $encoder %>
<%= form.hidden_field $tek=params[$encoder] || {"text"=>"", "key"=>5} %>


<% 
puts 'begins here'
puts $tek['text']
puts $tek['key']


init=$tek['text']
key=$tek['key'].to_i
key=5 if $tek['key'].size==0 
####Внимание!!!! Нужно как-то запретить ставить нолик. Либо вместо этого использовать что-то другое.

puts 'init'
puts init
puts 'ki'
puts key
puts key.class

signa=("f"*key).to_i(16).to_s(10).size.to_s.to_i



puts "Into hex:"
enko= init.unpack("H*")[0]
puts enko

#вычисление количества недостающх до квадратной таблицы символов
qwant=-enko.length%key
puts qwant
enko='0'*qwant+enko
puts enko

puts "Splitting into 5 charachters:"
enkoma =enko.scan(/.{#{key}}/)
#enkoma =enko.split(/(.{5})\s/)
puts enkoma
puts "Now converting the array into dec:"
enkoma.map! do |c|
c=c.to_i(16).to_s(10).rjust(signa,'0')
end
puts
puts enkoma
puts
puts "Now join it into one block:"
enko=enkoma.join
puts enko
puts
puts "Now convert it into hex again:"
converted=enko.to_i(10).to_s(16)

puts $tek['text']

puts $tek['text'].size
puts enko.size


%>

  <%= form.label 'decoded' %>
  <%= form.text_area :text, value: $tek['text'] %><P>
    <%= form.text_area :encoded, value: converted  %>

    <%= form.label 'key' %>
    <%= form.text_field :key, value: $tek['key'] %>
        <P>
	<%=
	if params['commit']!='Encode!' then 

form.submit "Encode!"  

else 

link_to "<button>New Encode!</button>".html_safe, coder_path, :method => :get
end


%>
  
<P>
<%# form.label :text, value: $tek %><P>


<div class="field">

</div>
   
<% end  %>

app/views/he-small-keys/_nome.erb
<%= form_for $decoder do |form| %>
<%= form.label $decoder %>
<%= form.hidden_field $enko=params[$decoder] || {"enk"=>"", "key"=>5} %>


<% 
puts 'enko here'
puts $enko['enk']
puts $enko['key']
puts $enko


enko=$enko['enk']
key=$enko['key'].to_i
key=5 if $enko['key'].size==0 
####Внимание!!!! Нужно как-то запретить ставить нолик. Либо вместо этого использовать что-то другое.

puts 
puts 
puts ''
puts key
puts key.class

signa=("f"*key).to_i(16).to_s(10).size




puts "Convert into DEC:"
enko=enko.to_i(16).to_s(10)
puts enko

puts "Adding zeroes for square table"
enko='0'*(-enko.size%signa)+enko
puts enko

puts "Splitting into signa-amount of charachters:"
enkoma =enko.scan(/.{#{signa}}/)
puts enkoma

puts "Now converting the array into hex:"
enkoma.map! do |c|
c=c.to_i(10).to_s(16).rjust(key,'0')
end
puts
puts enkoma

#puts "Now removing placeholder zeroes:"
#enkoma[0]=enkoma[0].to_i
#puts enkoma



puts "Now join it into one block:"
enko=enkoma.join
puts enko

puts
#qwant=-enko.length%key
#puts qwant

#enko=enko[qwant..-1]

puts "Removing leading zeroes"
enko

enko=enko.sub(/^[0]+/,'')

puts "Converting back to human language:"
deko= [enko].pack("H*")
puts enko


#$enko['text']=enko

%>


  <%= form.label 'decoded' %>
<%= form.text_area :enk, value: $enko['enk']  %><P>
<%= text_area_tag 'decoded', deko   %>


    <%= form.label 'key' %>
    <%= form.text_field :key, value: $enko['key'] %>
        <P>
  <%= form.submit "Decode!"  %>
<P>
<%# form.label :text, value: $enko  %>

<%# form.text_field [$decoder], value:'teet'%>

<%#
puts 'this is for debug'
puts params[$decoder]
puts 'reset'
params.delete(/\D/) if params[$decoder]
puts params[$decoder]

%>

<%= 
puts "kotrolёr"
#puts params[$decoder].methods
puts 'bordюr'
params[$decoder] = params[$decoder].to_yaml if params[$decoder]
#params=[]

puts "kotrolёr"
puts params

puts params['commit']



 %>

<div class="field">

</div>
   
<% end  %>

app/views/he-small-keys/about.html.erb
<p>Now we change the value again!</p>
<% $test='I\'m a help page!'%>
<%= $test%>

app/views/he-small-keys/coder.html.erb
<p>Lets change the value, now it is</p>

<P>
<table>
<tr>
<td>
<%= render 'encoder' %>

</td>
<td>
<%= render 'decoder' %>



</td>

</tr>
</table>



<P>

app/views/he-small-keys/home.html.erb
<p>Here is the value:</p>
<%= $test%>

app/views/he/_decoder.html.erb
#encoding: utf-8
<%= form_for $decoder do |form| %>
<% form.label $decoder %>
<%= form.hidden_field $enko=params[$decoder] || {"enk"=>"", "key"=>''} %>


<% 
puts 'enko here'
puts $enko['enk']
puts $enko['key']
puts $enko


enko=$enko['enk'].force_encoding('utf-8')
kiis=$enko['key'].force_encoding('utf-8')
puts kiis


#This is only for heroku originaly you could set kiis.size to 7:
puts 'key size validation block'
#if kiis.size<=7 then
if (kiis.size<=4) and (enko.size<=99999) then

kiis=kiis.codepoints.join
puts kiis

kiis=kiis.reverse
puts kiis

kiis=kiis.split('')
puts kiis.to_s

puts 'beginning kiis block'

kiis.each do |key|

key=key.to_i 
if key!=0 then

signa=("f"*key).to_i(16).to_s(10).size




puts "Convert into DEC:"
enko=enko.to_i(16).to_s(10)
puts enko

puts "Adding zeroes for square table"
enko='0'*(-enko.size%signa)+enko
puts enko

puts "Splitting into signa-amount of charachters:"
enkoma =enko.scan(/.{#{signa}}/)
puts enkoma

puts "Now converting the array into hex:"
enkoma.map! do |c|
c=c.to_i(10).to_s(16).rjust(key,'0')
end
puts
puts enkoma

#puts "Now removing placeholder zeroes:"
#enkoma[0]=enkoma[0].to_i
#puts enkoma



puts "Now join it into one block:"
enko=enkoma.join
puts enko

puts
#qwant=-enko.length%key
#puts qwant

puts 'ending kiis block'

end
end

#enko=enko[qwant..-1]

puts "Removing leading zeroes"
enko

enko=enko.sub(/^[0]+/,'')





puts "Converting back to human language:"
deko= [enko].pack("H*")
puts deko
puts params
puts deko.encoding
deko.force_encoding('UTF-8')
puts deko
puts deko.encoding






#$enko['text']=enko

puts 'ending key size validation block'
else 



if (kiis.size>4) then
$enko['key']='Your key is too big. Change it and try again!'
end

if (enko.size>999999) then
deko='Your text is too big. Change it and try again!'
end

end

%>


  <%= form.label 'Encoded text: (Max:99999)' %>
  <%= form.text_area :enk, value: $enko['enk']  %><P>
    <%= form.label 'Decoded text:' %>

<%= text_area_tag 'decoded', deko   %>


    <%= form.label 'key: (Max: 4)' %>
    <%= form.text_field :key, value: $enko['key'] %>
        <P>
  <%= 
  	if params['commit']!='Decode!' then 
  
form.submit "Decode!", class: 'calculate'  
else 

link_to "<button>New Decode!</button>".html_safe, coder_path, :method => :get
end


%>
<P>

<%#
puts 'this is for debug'
puts params[$decoder]
puts 'reset'
params.delete(/\D/) if params[$decoder]
puts params[$decoder]

%>



<div class="field">

</div>
   
<% end  %>

app/views/he/_encoder.html.erb
#encoding: utf-8
<%= form_for $encoder do |form| %>
<% form.label $encoder %>
<%= form.hidden_field $tek=params[$encoder] || {"text"=>"", "key"=>''} %>


<% 
puts 'begins here'
puts $tek['text']
puts $tek['key']




init=$tek['text'].force_encoding('utf-8')
kiis=$tek['key'].force_encoding('utf-8')
puts kiis



#This is only for heroku originaly you could set kiis.size to 7:
puts 'key size validation block'
#if kiis.size<=7 then
if (kiis.size<=4) and (init.size<=4000) then

puts "Into hex:"
enko= init.unpack("H*")[0]
puts enko

puts puts

kiis=kiis.codepoints.join
puts kiis


kiis=kiis.split('')
puts kiis.to_s

puts 'beginning kiis block'

kiis.each do |key|

key=key.to_i 
if key!=0 then


puts 'enko'
puts enko
puts 'ki'
puts key
puts key.class

signa=("f"*key).to_i(16).to_s(10).size.to_s.to_i





#вычисление количества недостающх до квадратной таблицы символов
qwant=-enko.length%key
puts qwant
enko='0'*qwant+enko
puts enko

puts "Splitting into 5 charachters:"
enkoma =enko.scan(/.{#{key}}/)
#enkoma =enko.split(/(.{5})\s/)
puts enkoma
puts "Now converting the array into dec:"
enkoma.map! do |c|
c=c.to_i(16).to_s(10).rjust(signa,'0')
end
puts
puts enkoma
puts
puts "Now join it into one block:"
enko=enkoma.join
puts enko



puts
puts "Now convert it into hex again:"
enko=enko.to_i(10).to_s(16)

puts 'ending kiis block'

end
end

converted=enko


puts $tek['text']

puts $tek['text'].size
puts enko.size

puts 'ending key size validation block'
else 

if (kiis.size>4) then
$tek['key']='Your key is too big. Change it and try again!'
end

if (init.size>4000) then
converted='Your text is too big. Change it and try again!'
end

end



%>

  <%= form.label 'Original text: (Max:4000)' %>
  <%= form.text_area :text, value: $tek['text'] %><P>
  <%= form.label 'Encoded text:' %>
    <%= form.text_area :encoded, value: converted  %>

    <%= form.label 'key: (Max: 4)' %>
    <%= form.text_field :key, value: $tek['key'] %>
        <P>
	<%=
	if params['commit']!='Encode!' then 

form.submit "Encode!", class: 'calculate'  

else 

link_to "<button>New Encode!</button>".html_safe, coder_path, :method => :get
end


%>
  
<P>
<%# form.label :text, value: $tek %><P>


<div class="field">

</div>

   
<% end  %>

app/views/he/_nome.erb
<%= form_for $decoder do |form| %>
<%= form.label $decoder %>
<%= form.hidden_field $enko=params[$decoder] || {"enk"=>"", "key"=>5} %>


<% 
puts 'enko here'
puts $enko['enk']
puts $enko['key']
puts $enko


enko=$enko['enk']
key=$enko['key'].to_i
key=5 if $enko['key'].size==0 
####Внимание!!!! Нужно как-то запретить ставить нолик. Либо вместо этого использовать что-то другое.

puts 
puts 
puts ''
puts key
puts key.class

signa=("f"*key).to_i(16).to_s(10).size




puts "Convert into DEC:"
enko=enko.to_i(16).to_s(10)
puts enko

puts "Adding zeroes for square table"
enko='0'*(-enko.size%signa)+enko
puts enko

puts "Splitting into signa-amount of charachters:"
enkoma =enko.scan(/.{#{signa}}/)
puts enkoma

puts "Now converting the array into hex:"
enkoma.map! do |c|
c=c.to_i(10).to_s(16).rjust(key,'0')
end
puts
puts enkoma

#puts "Now removing placeholder zeroes:"
#enkoma[0]=enkoma[0].to_i
#puts enkoma



puts "Now join it into one block:"
enko=enkoma.join
puts enko

puts
#qwant=-enko.length%key
#puts qwant

#enko=enko[qwant..-1]

puts "Removing leading zeroes"
enko

enko=enko.sub(/^[0]+/,'')

puts "Converting back to human language:"
deko= [enko].pack("H*")
puts enko


#$enko['text']=enko

%>


  <%= form.label 'decoded' %>
<%= form.text_area :enk, value: $enko['enk']  %><P>
<%= text_area_tag 'decoded', deko   %>


    <%= form.label 'key' %>
    <%= form.text_field :key, value: $enko['key'] %>
        <P>
  <%= form.submit "Decode!"  %>
<P>
<%# form.label :text, value: $enko  %>

<%# form.text_field [$decoder], value:'teet'%>

<%#
puts 'this is for debug'
puts params[$decoder]
puts 'reset'
params.delete(/\D/) if params[$decoder]
puts params[$decoder]

%>

<%= 
puts "kotrolёr"
#puts params[$decoder].methods
puts 'bordюr'
params[$decoder] = params[$decoder].to_yaml if params[$decoder]
#params=[]

puts "kotrolёr"
puts params

puts params['commit']



 %>

<div class="field">

</div>
   
<% end  %>

app/views/he/about.html.erb
<b> Short Hexadem FAQ</b><P><P><P><P><P>

<table id='aboutt'>
<tr>
<td>
What is Hexadem?
</td>
<td>
It's just a coder web-application.

</td>
</tr>
<tr>
<td>
How to use Hexadem?
</td>
<td>
To encode and decode the text you need to have
input the text and the key. 


</td>
</tr>
<tr>
<td>
It doesn't hide your data from the FBI and KGB
</td>
<td>
But it will hide your text from ordinary people.

</td>
</tr>
<tr>
<td>
Your data is not collected.
</td>
<td>
It is not saved anywhere on the page nor in a database. 
When you leave or reload the page all your data is gone.

</td>
</tr>
<tr>
<td>
Does it really help?
</td>
<td>
It helps to some extent. There are tons of custom
ways to encode and encrypt your data. It is safe
as long as you don't tell others about Hexadem.

</td>
</tr>

<tr>
<td>
Disadvantages?
</td>
<td>
Yes. The length of the encoded data significantly 
depends on the key. 33 symbols of your text may 
turn into 156692 symbols which is around 150 Kilobytes.

</td>
</tr>
<tr>
<td>
This is ridiculus. Maximum key length is 4! It's like a PIN!
</td>
<td>
This site is located on Heroku and the platform has some limitations. Originally, key length was restricted to 7 symbols. You can find the source code on the <a href='https://github.com/gearcoded/hexadem'>GitHub</a>. Please remember that ruby code does not have limitations at all. You are limited only to your CPU and RAM.

</td>
</tr>
<tr>
<td>
Then why did you create this web-application?

</td>
<td>
It was a project to learn more about ruby and rails 
and I really enjoyed not only making my ideas alive,
but also predicting how people could use the application
and fixing bugs.


</td>
</tr>
</table>

<P><P><P>
<h3 align='center'>Beware!<P> Never tell anybody about this application! <P>
Your data safety is under risk!
</h3>

<P><P><P>

app/views/he/coder.html.erb
<p>Encode or decode?</p>

<P>
<table id='codert'>
<tr>
<td><P align=center>::: Encoding section :::</P><P>
<%= render 'encoder' %>

</td>
<td style='border-left: 2px dashed rgba(158,139,82,.9);'><P align=center>::: Decoding section :::</P><P>
<%= render 'decoder' %>



</td>

</tr>
</table>




  <div class= 'popup' id="page-mask" ></div>
  <div class= 'popup' id="window" align=center>Large text and long keys increase calculation time.<P>
  Please don't leave the page, just wait... 





  <%= image_tag "hive.png", alt: 'hive', size: '128x128', class: 'hive' %>

  <%= image_tag "123.png", alt: '123', size: '128x128', class: 'exps' %>  
  </div>



<P>
 <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
  
  <script>
  $(document).ready(function(){
$( ".calculate" ).click(function(){
  $('.popup').show();
  });
  });
  </script>

app/views/he/home.html.erb
<table class='homepix'>
<tr>
<td>
<%= link_to image_tag("question.svg", alt: 'question', size: '128x128', class: 'jump'), about_path %>
</td>
<td>
<%= link_to image_tag( "gear.svg", alt: 'gear', size: '128x128', class: 'gear'), coder_path, data: { turbolinks: false } %>
</td>
</tr>
</table>








  <% image_tag "flower.png", alt: 'flower', size: '128x128', class: 'flower' %>





  <% image_tag "hive.png", alt: 'hive', size: '128x128', class: 'hive' %>

  <% image_tag "droplet.png", alt: 'droplet', size: '128x128', class: 'droplet' %>

  <% image_tag "123.png", alt: '123', size: '128x128', class: 'exps' %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container pull-left">
      <%= link_to "HEXADEM", root_path, id: "logo" %>
      <nav>
        <ul class="nav push-right">
          <li><%= link_to "About",    about_path %></li>
          <li><%= link_to "Coder",    coder_path, data: { turbolinks: false } %></li>
          <li><%= link_to "Home", root_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hexadem</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>